name: test

on:
  - push
  - workflow_dispatch

jobs:
  call-workflow:
    uses: enveda/reusable-workflows/.github/workflows/uv-test-and-pre-commit.yml@v3
    secrets: inherit
    with:
      python-versions: '["3.10"]'
