name: uv-build-and-upload

on:
  workflow_dispatch:
  release:
    types: [published]

jobs:
  uv-build-and-upload:
    uses: enveda/reusable-workflows/.github/workflows/uv-build-and-upload.yml@v3
    secrets: inherit
    with:
      python-version: "3.10"
